"""How to delete an account, per site, from the JustDeleteMe dataset.

JustDeleteMe (https://github.com/jdm-contrib/jdm, MIT) documents the deletion
process for ~2600 services, each tagged with the domains it covers. The vendored
copy in data/ is regenerated by scripts/update_jdm.py; see data/LICENSE-JDM.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from importlib import resources
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

DIFFICULTIES = ("easy", "medium", "hard", "limited", "impossible")


@dataclass(frozen=True)
class Remediation:
    service: str
    url: str
    difficulty: str
    notes: str = ""
    email: str = ""
    email_subject: str = ""
    email_body: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def host_of(url: str) -> str:
    """Lowercase host without port or a leading ``www.``; empty if unparseable."""
    try:
        host = (urlparse(url).hostname or "").lower()
    except ValueError:
        return ""
    return host[4:] if host.startswith("www.") else host


def _parents(host: str) -> list[str]:
    """``a.b.example.com`` -> [a.b.example.com, b.example.com, example.com].

    Stops at two labels, so a bare suffix like ``com`` is never a match. Needed
    because many profile URLs live on a per-user subdomain (user.tumblr.com).
    """
    labels = host.split(".")
    return [".".join(labels[i:]) for i in range(max(0, len(labels) - 1)) if len(labels) - i >= 2]


class RemediationIndex:
    def __init__(self, entries: list[dict[str, Any]]) -> None:
        self._by_host: dict[str, Remediation] = {}
        for entry in entries:
            if not isinstance(entry, dict) or not entry.get("url"):
                continue
            remediation = Remediation(
                service=str(entry.get("name", "")),
                url=str(entry["url"]),
                difficulty=str(entry.get("difficulty", "unknown")),
                notes=str(entry.get("notes", "")),
                email=str(entry.get("email", "")),
                email_subject=str(entry.get("email_subject", "")),
                email_body=str(entry.get("email_body", "")),
            )
            for domain in entry.get("domains") or ():
                key = host_of(f"https://{domain}")
                # First entry wins: JDM lists a few services under shared domains.
                if key and key not in self._by_host:
                    self._by_host[key] = remediation

    def __len__(self) -> int:
        return len(self._by_host)

    @classmethod
    def load(cls, path: Path | None = None) -> RemediationIndex:
        if path is not None:
            text = Path(path).read_text(encoding="utf-8")
        else:
            text = (resources.files("whoseeme.data") / "jdm_sites.json").read_text("utf-8")
        return cls(json.loads(text))

    def lookup(self, url: str) -> Remediation | None:
        """Deletion guidance for the service a profile URL belongs to, if known."""
        host = host_of(url)
        if not host:
            return None
        for candidate in _parents(host):
            if candidate in self._by_host:
                return self._by_host[candidate]
        return None
